FROM openjdk:13-alpine

ARG JAR_BASE_NAME=${JAR_BASE_NAME}
ARG BUILD_VERSION=${BUILD_VERSION}
ARG JAR_FILE=$JAR_BASE_NAME-$BUILD_VERSION.jar

ARG START_SCRIPT=start.sh

COPY ${JAR_FILE} app.jar
COPY ${START_SCRIPT} start.sh

ENTRYPOINT ["./start.sh"]