#!/bin/sh

java -DOWNER=$1 -DTOKEN=$2 -DPREFIX=$3 -DINACTIVE_THRESHOLD=$4 -DTASK_INACTIVE_FIXED_DELAY=$5 -DRABBIT_HOSTNAME=$6 -DRABBIT_USERNAME=$7 -DRABBIT_PASSWORD=$8 -DRABBIT_VIRTUALHOST=$9 -DRABBIT_CONNECTION_TIMEOUT=$10 -DRABBIT_REQUEST_HEARTBEAT=$11 -DRABBIT_QUEUE_TTL=$12 -jar ./app.jar